### ISSUE TITLE
There is no object-tools block in change_list.html

### ISSUE THREAD

**Issue by rmoorman** [barszczmm/django-wpadmin#10]
I just tried to use the django-wpadmin app together with the django-reversion app and noticed that the "Recover deleted [object name plural]" link was missing. Django reversion obviously uses the object-tools  block to add this link to the change list. And because the django-wpadmin's change_list.html is not using this block, nothing is being displayed.

Is there any proper solution for this?

Thank you very much in advance.

Best regards,
Rico Moorman

**Comment by barszczmm** [comment]
Hi. 

Thanks for reporting this. I should have some free time in next few days, so I will investigate this issue and provide update with solution. I'll try to do it as soon as possible.

**Comment by rmoorman** [comment]
That would be great. Let me know if you need some feedback or the like.

**Comment by barszczmm** [comment]
Hi.

I've just released new version (1.7.1) of Django WP Admin which addresses object-tools block issue and adds some translations and small updates. You can install it both from GitHub and from PyPI. Please let me know if "Recover deleted..." link is displayed now as expected.

**Comment by rmoorman** [comment]
Works for me! There seems to be one little visual regression though:
![visual regression](https://cloud.githubusercontent.com/assets/219695/6791116/f938f906-d1ac-11e4-9658-964d6a893b88.png)

**Comment by barszczmm** [comment]
Ah yes. I didn't check all templates properly. I'll fix it tomorrow. Thanks for reporting.

**Comment by barszczmm** [comment]
New version was just released (it also includes your translation - thanks for that :) ). Please test it and let me know if it is ok now.

**Comment by rmoorman** [comment]
The new version is ok now :-). Thank you!
And I am glad that I could help a little too.

**Comment by barszczmm** [comment]
So I can close this :)
