### ISSUE TITLE
Hey, are you still working on it?

### ISSUE THREAD

**Issue by COLABORATI** [barszczmm/django-wpadmin#26]
Are you working on it? This is a fine project, should not die!

**Comment by barszczmm** [comment]
Hi. I definitely don't want this project to be dead, but it's very hard for me to find some free time to test it with latest Django versions and to push some updates (I have lot of work and lot of private activities right now). But I have some plans for future updates of this project and want to check all pending PR. I think I will release new version within one month (in September).

Thanks for caring and for patience :)

**Comment by CARocha** [comment]
Hi, you need any help for update this proyects? i have free time!

**Comment by barszczmm** [comment]
I'm back and maintaining this again. Plans are in [TODO](https://github.com/barszczmm/django-wpadmin#todo). Thanks.
