### ISSUE TITLE
jazzband maintain this project

### ISSUE THREAD

**Issue by CARocha** [barszczmm/django-wpadmin#32]
Hi @barszczmm 
Look like lots of people want to help to maintain this repository maybe you can consider a project transfer to jazzband ?

https://github.com/jazzband

Just a suggestion!

**Comment by barszczmm** [comment]
Hi

Thanks for the suggestion, I did not know about the jazzband. I like the idea, but I decided to actively maintain this project again. However if I'll ever leave it unmaintained for so long again I will probably transfer it to jazzband.
