### ISSUE TITLE
Unable to create jQuery modal dialog

### ISSUE THREAD

**Issue by bratislav** [barszczmm/django-wpadmin#7]
Hi,

I'm trying to create a modal dialog to display when the admin page is ready using this code in the change_list.txt template :

```
<script type="text/javascript">
    
    (function($) {
        $(document).ready(function($) {
             $("#dialog").dialog({
                modal: true,
                autoOpen: true
            });
        });
    })(django.jQuery);
</script>
```
..but when I load the page I'm getting "Uncaught TypeError: undefined is not a function".

Dialog is defined in change_list.txt (which is overriden) inside block content like this :
``` 
<div id="dialog" title="Title">This is dialog.</div>
```

What should I do to set this dialog to show?

**Comment by barszczmm** [comment]
I'm closing this as I can not help without more information.
