### ISSUE TITLE
Login site showing black in Firefox

### ISSUE THREAD

**Issue by kouete** [barszczmm/django-wpadmin#8]
First wanted to congratulate for the great job before posting the issue I have experienced with Firefox.
In fact, the Login site is showing black in Firefox. This can be reproduced by calling: 
http://django-wpadmin.dev.barszcz.info/adminpanel/
in Firefox.
Cheers
![wpadmin_login_firefox_login_issue](https://cloud.githubusercontent.com/assets/9654641/4974259/1e82c490-68ca-11e4-9133-326803f65bc2.png)

**Comment by barszczmm** [comment]
I'm closing this as there are no new informations, I can not reproduce this and no one else reported same or similar issue.
